config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    resources :users do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
    resources :genres
    resources :labels
    resources :artists
    resources :reviews
    resources :musics
    resources :discs
  end


  resources :admins do
    collection do
      get :home
    end
  end

  resources :users do
    resources :addresses
    resources :carts
    resources :orders do
      resources :order_details
    collection do
      get :success
    end
  end
  end


  resources :products, only:[:index, :show, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resources :artists
  resources :favorites
  resources :reviews
  resources :labels
  resources :genres

  post 'reviews' => 'reviews#create'
  delete 'reviews' => 'reviews#destroy'
  post 'reviews/:id/edit' => 'admins/reviews#edit'
  post "reviews/:id/update" => "admins/reviews#update"



end

app/models/address.rb
class Address < ApplicationRecord

	belongs_to :user
	validates :postalcode,presence: true, length:{ is: 7 }
	validates :address,presence: true, length:{ in: 1..100 }
	validates :name,presence: true, length:{ in: 1..50 }


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def user
        User.unscoped{super}
  	end

end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :musics
	validates :artist, presence: true, length:{ in: 1..50 }

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user

	belongs_to :product


end

app/models/disc.rb
class Disc < ApplicationRecord

	belongs_to :product, inverse_of: :discs

	has_many :musics, inverse_of: :disc
    accepts_nested_attributes_for :musics, reject_if: :all_blank, allow_destroy: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :products
	validates :genre, presence: true, length:{ in: 1..50 }


end

app/models/label.rb
class Label < ApplicationRecord

	has_many :products
	validates :label, presence: true, length:{ in: 1..100 }


end

app/models/music.rb
class Music < ApplicationRecord

	belongs_to :disc, inverse_of: :musics

	belongs_to :artist
	validates :title, presence: true, length:{ in: 1..50 }


end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :user

	def user
        User.unscoped{super}
    end

	has_many :order_details

	enum order_status:{受付: 0, 準備中: 1, 出荷済: 2,}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

	belongs_to :order



	belongs_to :product

    def product
        Product.unscoped{super}
    end

end

app/models/product.rb
class Product < ApplicationRecord

    acts_as_paranoid


	has_many :favorites, dependent: :destroy
    has_many :reviews
    has_many :carts, dependent: :destroy
    has_many :discs, inverse_of: :product

    accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

    belongs_to :label
    belongs_to :genre

    attachment :image


    validates :stock_quantity, numericality: {greater_than_or_equal_to: 0}


    enum sales_status:{販売中: 0, 販売停止中: 1,}



def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
end

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :product
	validates :review,presence: true, length:{ in: 1..200 }



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid

  def user
      User.unscoped{super}
  end

  has_many :addresses
  has_many :orders
  has_many :carts
  has_many :favorites, dependent: :destroy
  has_many :reviews,dependent: :destroy

  validates :last_name,presence: true, length:{ in: 1..50 }
  validates :first_name,presence: true, length:{ in: 1..50 }
  validates :last_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postalcode,presence: true, length:{is:7},format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}
  validates :telephone_number,presence: true,length:{ in: 9..20 },format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/home.html.erb
  <head>
    <meta charset="utf-8">
    <title>機能一覧</title>
  </head>
  <body>
    <div class="container">
    <div class="row">
    <div class="col-md-6 col-md-offset-3"  style="margin-top: 50px;" >

      <% if notice %>
          <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
              <span class="sr-only">close</span>
            </button>
            <%= notice %>
          </div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        <%= alert %>
      </div>
      <% end %>

  <%= link_to "商品登録", new_admins_product_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>
  <%= link_to "アーティスト登録", new_admins_artist_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>
  <%= link_to "商品一覧", admins_products_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>
  <%= link_to "購入履歴", admins_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>
  <%= link_to "ユーザー一覧", admins_users_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>

</div>
</div>
</div>
</body>

app/views/admins/index.html.erb
<div class="container">
	<h3><strong>購入履歴一覧</strong></h3>
	<table class="table table-bordered">
		<thead>
			<tr >
				<th>No</th>
				<th>購入者</th>
				<th>会員情報</th>
				<th style="text-align: center;">
				  購入日
				</th>
				<th style="text-align: center;">
				  購入商品詳細
				</th>
				<th style="text-align: center;">
				  購入価格総計
				</th>
				<th style="text-align: center;">
				  送付先
				</th>
				<th colspan="2" style="text-align: center;" >
				  販売ステータス
				</th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
			<tr>
				<td><%= order.id %></td>
				<td><%= order.user.last_name %><%= order.user.first_name %></td>
				<td>
					<% if order.user.deleted_at == nil %>
					<p>入会</p>
				    <% else %>
				    <p>退会</p>
				    <% end %>
				</td>
				<td><%= order.created_at.strftime('%Y/%m/%d') %></td>
				<td>
					<% order.order_details.each do |order_detail| %>
	                <%= order_detail.product.album %>： 購入枚数<%= order_detail.quantity %>枚
	                ¥<%= get_subtotal(order_detail) %><br>
	                <% end %>
                </td>
				<td>￥<%= order.subtotal_price %></td>
				<td>
					〒<%= order.postalcode %><br>
					<%= order.address %><br>
					<%= order.last_name %>
				</td>
				<%= form_for order, url: admins_user_order_path(user_id: order.user_id, id: order.id) do |o| %>
				<td style="text-align: center;">
				  <%= o.select :order_status, Order.order_statuses.keys.map{|status| [status, status]}, {:prompt => order.order_status} %>
				</td>
				<td style="text-align: center;">
				  <%= o.submit "変更", class: "btn btn-default" %>
				</td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<div class="text-center">
	<%= paginate @orders, class: "paginate" %>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class="col-md-8 col-md-offset-10" style="padding-top: 10px;padding-bottom: 10px;">
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <p class="" style="margin-top:5px;margin-bottom:0px;">Forgot your password? <%= link_to "click here", new_password_path(resource_name) %></p>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>