config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    resources :users do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
    resources :genres
    resources :labels
    resources :artists
    resources :reviews
    resources :musics
    resources :discs
  end


  resources :admins do
    collection do
      get :home
    end
  end

  resources :users do
    resources :addresses
    resources :carts
    resources :orders do
      resources :order_details
    collection do
      get :success
    end
  end
  end


  resources :products, only:[:index, :show, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resources :artists
  resources :favorites
  resources :reviews
  resources :labels
  resources :genres

  post 'reviews' => 'reviews#create'
  delete 'reviews' => 'reviews#destroy'
  post 'reviews/:id/edit' => 'admins/reviews#edit'
  post "reviews/:id/update" => "admins/reviews#update"



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid

  def user
      User.unscoped{super}
  end

  has_many :addresses
  has_many :orders
  has_many :carts
  has_many :favorites, dependent: :destroy
  has_many :reviews,dependent: :destroy

  validates :last_name,presence: true, length:{ in: 1..50 }
  validates :first_name,presence: true, length:{ in: 1..50 }
  validates :last_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postalcode,presence: true, length:{is:7},format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}
  validates :telephone_number,presence: true,length:{ in: 9..20 },format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}


end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!
  def index
    @user = User.unscoped.all
    @users = @user.page(params[:page]).reverse_order.per(20)
  end



  def show
  	@user = User.unscoped.find(params[:id])
  	@address = Address.new
    @addresses = @user.addresses.page(params[:addresses_page]).reverse_order.per(5)
    @orders = @user.orders.page(params[:orders_page]).reverse_order.per(5)
  end



  private

    def user_params
        params.require(:user).permit(:address_id, :last_name, :first_name, :last_name_k, :first_name_k, :postalcode, :address, :telephone_number, :email, :password, :user_status)
    end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def show
		@user = User.unscoped.find(params[:id])
		if current_user.id != @user.id
	    redirect_to root_path
	    end
		@address = Address.new
		@addresses = @user.addresses.page(params[:addresses_page]).reverse_order.per(5)
		@favorites = @user.favorites.all
		@orders = @user.orders.page(params[:orders_page]).reverse_order.per(5)
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		sign_in(@user, bypass: true)
		redirect_to user_path(@user.id)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end

    private

    def user_params
        params.require(:user).permit(:address_id, :last_name, :first_name, :last_name_k, :first_name_k, :postalcode, :address, :telephone_number, :email, :password)
    end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/index.html.erb
<div class="container">
	<h3><strong>顧客一覧</strong></h3>
	<body>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>名前</th>
				<th>電話番号</th>
				<th>メール</th>
				<th>会員情報</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= link_to user.last_name + user.first_name , admins_user_path(user.id), :style=>"color:#777;text-decoration: none;" %></td>
				<td><%= user.telephone_number %></td>
				<td><%= user.email %></td>
				<td>
					<% if user.deleted_at == nil %>
					<p>入会</p>
				    <% else %>
				    <p>退会</p>
				    <% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</body>
</div>

app/views/admins/users/show.html.erb
<div class="container">

      <div class="row">
      <div class="col-md-10 col-md-offset-1">
      	 <div class="col-lg-5" >
      	 	<%= render 'users/userinfo' %>
      	 </div>
      	 <div class="col-lg-7" >
              <h3 class=""><strong>送付先住所</strong></h3>
                  <table class="table ">

                  <thead>
                        <th>郵便番号</th>
                        <th>住所</th>
                        <th>宛名</th>
                  </thead>
                    <% @addresses.each do |address| %>
                  <tbody>
                   <td><%= address.postalcode %></td>
                   <td><%= address.address %></td>
                   <td><%= address.name %></td>
                  </tbody>
                  <% end %>
                  </table>

                  <div class="text-center">
                    <%= paginate @addresses, param_name: 'addresses_page', class: "paginate" %>
                  </div>
      	 </div>
      </div>
      </div>

      <div class="row">
            <div class="col-md-10 col-md-offset-1">
                  <h3 class="text-center"><strong>購入履歴</strong></h3>
                  <table class="table table-bordered">
                  <thead>
                  <tr>
                        <th>購入日</th>
                        <th>購入商品詳細</th>
                        <th>購入価格総計</th>
                        <th>送付先</th>
                        <th>ステータス</th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @orders.each do |order| %>
                  <tr>
                        <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                        <td>
                              <% order.order_details.each do |order_detail| %>
                              <%= order_detail.product.album %> <%= order_detail.quantity %>枚
                               ¥<%= get_subtotal(order_detail) %><br>
                              <% end %>
                        </td>
                        <td>￥<%= order.subtotal_price %></td>
                        <td>
                              〒<%= order.postalcode %><br>
                              <%= order.address %><br>
                              <%= order.last_name %>
                        </td>
                        <td><%= order.order_status %></td>
                  </tr>
                  <% end %>
                  </tbody>
                  </table>
                   <div class="text-center">
                    <%= paginate @orders, param_name: 'orders_page', class: "paginate" %>
                  </div>
            </div>
      </div>

</div>