config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    resources :users do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
    resources :genres
    resources :labels
    resources :artists
    resources :reviews
    resources :musics
    resources :discs
  end


  resources :admins do
    collection do
      get :home
    end
  end

  resources :users do
    resources :addresses
    resources :carts
    resources :orders do
      resources :order_details
    collection do
      get :success
    end
  end
  end


  resources :products, only:[:index, :show, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resources :artists
  resources :favorites
  resources :reviews
  resources :labels
  resources :genres

  post 'reviews' => 'reviews#create'
  delete 'reviews' => 'reviews#destroy'
  post 'reviews/:id/edit' => 'admins/reviews#edit'
  post "reviews/:id/update" => "admins/reviews#update"



end

app/models/address.rb
class Address < ApplicationRecord

	belongs_to :user
	validates :postalcode,presence: true, length:{ is: 7 }
	validates :address,presence: true, length:{ in: 1..100 }
	validates :name,presence: true, length:{ in: 1..50 }


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    def user
        User.unscoped{super}
  	end

end

app/models/artist.rb
class Artist < ApplicationRecord

	has_many :musics
	validates :artist, presence: true, length:{ in: 1..50 }

end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :user

	belongs_to :product


end

app/models/disc.rb
class Disc < ApplicationRecord

	belongs_to :product, inverse_of: :discs

	has_many :musics, inverse_of: :disc
    accepts_nested_attributes_for :musics, reject_if: :all_blank, allow_destroy: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :product

end

app/models/genre.rb
class Genre < ApplicationRecord

	has_many :products
	validates :genre, presence: true, length:{ in: 1..50 }


end

app/models/label.rb
class Label < ApplicationRecord

	has_many :products
	validates :label, presence: true, length:{ in: 1..100 }


end

app/models/music.rb
class Music < ApplicationRecord

	belongs_to :disc, inverse_of: :musics

	belongs_to :artist
	validates :title, presence: true, length:{ in: 1..50 }


end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :user

	def user
        User.unscoped{super}
    end

	has_many :order_details

	enum order_status:{受付: 0, 準備中: 1, 出荷済: 2,}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

	belongs_to :order



	belongs_to :product

    def product
        Product.unscoped{super}
    end

end

app/models/product.rb
class Product < ApplicationRecord

    acts_as_paranoid


	has_many :favorites, dependent: :destroy
    has_many :reviews
    has_many :carts, dependent: :destroy
    has_many :discs, inverse_of: :product

    accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

    belongs_to :label
    belongs_to :genre

    attachment :image


    validates :stock_quantity, numericality: {greater_than_or_equal_to: 0}


    enum sales_status:{販売中: 0, 販売停止中: 1,}



def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
end

end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :product
	validates :review,presence: true, length:{ in: 1..200 }



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_paranoid

  def user
      User.unscoped{super}
  end

  has_many :addresses
  has_many :orders
  has_many :carts
  has_many :favorites, dependent: :destroy
  has_many :reviews,dependent: :destroy

  validates :last_name,presence: true, length:{ in: 1..50 }
  validates :first_name,presence: true, length:{ in: 1..50 }
  validates :last_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :first_name_k,presence: true, length:{ in: 1..50 },format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
  validates :postalcode,presence: true, length:{is:7},format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}
  validates :telephone_number,presence: true,length:{ in: 9..20 },format:{with:/\A[0-9]+\z/ ,message:'は数字で入力してください。'}


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!

	def index
	 @carts = Cart.where(user_id: current_user.id)
	 @user = current_user
	end

	def update
	 @cart = Cart.find(params[:id])
	 @cart.update!(cart_params)
	 redirect_to user_carts_path(@cart.user.id)
	end

	def destroy
	 cart = Cart.find(params[:id])
	 cart.destroy
	 redirect_to user_carts_path()
	end

	def create
		current_cart(params[:cart][:product_id])
		@cart.quantity += params[:cart][:quantity].to_i
	    @cart.user_id = current_user.id
	    @cart.save
	    redirect_to ('/')
    end


    private


    def cart_params
    	params.require(:cart).permit(:quantity, :product_id, :user_id)
    end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<% if @carts.blank? %>
				<div class="row">
					<h1 class="text-center" style="margin: 50px 0px;">カートが空です</h1>
				</div>
			<div class="col-md-6 col-md-offset-3">
				<div>
			 		<%= link_to "戻る", root_path, class: "btn btn-default btn-block" %>
				</div>
			</div>
		</div>
	</div>
</div>
	<% else %>

<% if alert %>
<div class="alert alert-danger alert-dismissible" role="alert">
	<button type="button" class="close" data-dismiss="alert">
		<span aria-hidden="true">&times;</span>
		<span class="sr-only">close</span>
	</button>
	<%= alert %>
</div>
<% end %>


<h1>カート内容</h1>
<table class="table">
	<tbody>
		<% @carts.each do |cart| %>
		<tr>
			<td>
				<div class="center-block" style="margin-top: 10px;margin-bottom: 10px;">
					<%=link_to product_path(cart.product.id) do %>
						<%= attachment_image_tag cart.product, :image, :fill, 150, 150, format: 'jpg' %>
					<% end %>
				</div>
				<% if cart.product.sales_status == "販売停止中" or cart.product.stock_quantity == 0 %>
					<p>販売停止中</p>
					<% else %>
						<%= cart.product.sales_status %>/在庫数<%= cart.product.stock_quantity %> 個
				<% end %>
			</td>
			<td>
				<div class="center-block" style="margin-top: 35px;margin-bottom: 35px;">
					<h3><%= cart.product.album %></h3>
					<%= form_for cart, url: user_cart_path(user_id: @user.id,id: cart.id) do |f| %>
					<%= f.number_field :quantity, min: 1, max: cart.product.stock_quantity , style:"height:32px; width:45px;border: 1px solid #adadad; border-radius: 5px;" %>
					<%= f.submit "変更", class: "btn btn-default" %>
					<%= link_to "削除","/users/#{@user.id}/carts/#{cart.id}",  class: "btn btn-danger", method: :delete %><br>
					<div class="center-block" style="margin-top: 10px;"><strong>小計　¥<%= get_subtotal(cart) %></strong></div>
					<% end %>
				</div>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
	    <div class="col-md-3"></div>
	    <div class="col-md-8">
			<h2 class="page-header">総計    ¥<%= get_price(@carts) %>（税込）</h2>
		</div>
		<div class="col-md-1" style="padding-top: 40px;">
				<%= link_to "購入", new_user_order_path, class: "btn btn-secondary", :style=>"background-color: #777;color: white;" %>
	    </div>
	</div>
</div>
<% end %>