config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admins do
    resources :users do
      resources :orders
    end
    resources :products do
      resources :reviews
    end
    resources :genres
    resources :labels
    resources :artists
    resources :reviews
    resources :musics
    resources :discs
  end


  resources :admins do
    collection do
      get :home
    end
  end

  resources :users do
    resources :addresses
    resources :carts
    resources :orders do
      resources :order_details
    collection do
      get :success
    end
  end
  end


  resources :products, only:[:index, :show, :create] do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  resources :artists
  resources :favorites
  resources :reviews
  resources :labels
  resources :genres

  post 'reviews' => 'reviews#create'
  delete 'reviews' => 'reviews#destroy'
  post 'reviews/:id/edit' => 'admins/reviews#edit'
  post "reviews/:id/update" => "admins/reviews#update"



end

app/models/product.rb
class Product < ApplicationRecord

    acts_as_paranoid


	has_many :favorites, dependent: :destroy
    has_many :reviews
    has_many :carts, dependent: :destroy
    has_many :discs, inverse_of: :product

    accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

    belongs_to :label
    belongs_to :genre

    attachment :image


    validates :stock_quantity, numericality: {greater_than_or_equal_to: 0}


    enum sales_status:{販売中: 0, 販売停止中: 1,}



def favorited_by?(user)
  favorites.where(user_id: user.id).exists?
end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
	before_action :authenticate_admin!

    def index
    	@products = Product.page(params[:page]).reverse_order.per(20)
    end

    def show
  		@product = Product.find(params[:id])
  		@genre = @product.genre
  		@label = @product.label
  		@discs = @product.discs
        @reviews = @product.reviews
  	end


  	def edit
  		@prduct = Product.find(params[:id])
  		@product = Product.find(params[:id])
  		@genre = @product.genre
  		@label = @product.label
  		@discs = @product.discs
        @reviews = @product.reviews
  	end


	  def new
	 	  @product = Product.new
	   	  @disc = @product.discs.build
	  	  @music = @disc.musics.build
	  end

	  def create
		  @product = Product.new(product_params)
		  @product.save

		if @product.stock_quantity == 0
			@product.sales_status = 1
		end

	  	  if @product.save
			flash[:notice] = "商品を登録しました。"
		    redirect_to admins_product_path(@product)
		else
			flash[:alert] = "商品登録に失敗しました。"
			render :new
		end
	  end

	  def update
	  	@product = Product.find(params[:id])
	  	@product.update!(product_params)

	  	if @product.stock_quantity == 0
			@product.sales_status = 1
		end

	  	if @product.update!(product_params)
	  	   redirect_to admins_product_path(@product)
	  	else
	  		flash[:alert] = "商品編集に失敗しました。"
			render :edit
		end
	  end

	  def destroy
	  	@product = Product.find(params[:id])
	  	@product.destroy
	  	redirect_to admins_products_path
	  end

	  def number?(str)
	  	Integer(str)
	  	track_number
	  rescue ArgumentError
	  	false
	end


	protected

	def product_params
		params.require(:product).permit(:album, :genre_id, :label_id, :image, :price, :stock_quantity, :sales_status,
			                            discs_attributes: [:id, :disc_number, :product_id, :_destroy,
			                            musics_attributes: [:id, :title, :track_number, :disc_id, :artist_id, :_destroy,
		                                 ]])
	end

	def params_int(product_params)
		product_params.each do |key,value|
			if integer_string?(value)
				product_params[key] = value.to_i
			end
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def show
		@product = Product.find(params[:id])
		@genre = @product.genre
		@label = @product.label
		@discs = @product.discs
		@reviews = @product.reviews
		@cart = Cart.new

		if user_signed_in?
			#カートの商品の在庫数の変更機能
			if Cart.where(user_id: current_user.id).find_by(product_id: @product.id)
	          @usercart = Cart.where(user_id: current_user.id).find_by(product_id: @product.id)
	          @temporary_quantity = @product.stock_quantity - @usercart.quantity
	        else
	        	@temporary_quantity = @product.stock_quantity
	        end
        end


		@review = Review.new

	end

	def index
		@products = Product.page(params[:page]).reverse_order.per(40)
	end

	protected

	def product_params
	  	params.require(:product).permit(:album, :genre_id, :label_id, :image, :price, :stock_quantity, :sales_status,
			                            discs_attributes: [:id, :disc_number, :product_id, :_destroy,
			                            musics_attributes: [:id, :title, :track_number, :disc_id, :artist_id, :_destroy,
		                                 ]])
	end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<div class="row">
	<div class="d-inline-block col-lg-12">

		<% if notice %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
          	<span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
          <%= notice %>
        </div>
    <% end %>
    <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert">
      	<span aria-hidden="true">&times;</span>
        <span class="sr-only">close</span>
      </button>
      <%= alert %>
    </div>
    <% end %>

		<% @search_products.each do |product| %>

		<div class="d-inline-block col-lg-3" style="margin: 30px 0 30px 0;">
			<%= link_to product_path(product.id) do %>
			<%= attachment_image_tag product, :image, :fill, 200, 200, format: 'jpg' %>
			<% end %>
			<div class="productdata">
				<p class="" style="margin: 10px 0px 0px 0px;"><%= product.album %></p>
				<p class="" style="margin: 0px 0px 0px 0px;"><%= product.label.label %></p>
				<% if product.sales_status == "販売停止中" or product.stock_quantity == 0 %>
                	<p class="" style="margin: 0px 0px 0px 0px;">販売停止中</p>
          		<% else %>
            		<p class="" style="margin: 0px 0px 0px 0px;">￥<%= get_producttax(product) %></p>
         		<% end %>
					<% product.discs.first(1).each do |disc| %>
					<% disc.musics.first(1).each do |music| %>
					<p class="" style="margin: 0px 0px 0px 0px;"><strong><%= music.artist.artist %></strong></p>
					<% end %>
			        <% end %>
			        <p class="" style="margin: 0px 0px 0px 0px;"><i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i><%= product.favorites.count %></p>
			</div>
		</div>
		<% end %>

	</div>
	</div>
</div>
<div class="text-center">
	<%= paginate @products, class: "paginate" %>
</div>

app/views/products/show.html.erb
<% if user_signed_in? %>

<div class="container">
	<div class="row">
    <div class="col-xs-1"></div>

		<div class="col-xs-6" >
      <div style="margin: 40px">
        <%= attachment_image_tag @product,:image, :fill,400,400 %>
      </div>
		</div>

   	 <div class="col-xs-4" style="margin-top: 40px">


   		<div >
        <p class="" style="margin: 0 0 0 0;"> <%= @genre.genre %> </p>
     		<h2 class="" style="margin: 15px 0 15px 0;"> <%= @product.album %> </h2>
     		<p class="" style="margin: 10px 0 10px 0;"> <%= @label.label %> </p>
     		<p class="" style="margin: 10px 0 10px 0;"> ¥<%= get_producttax(@product) %>（税込）</p>
        <% if @product.favorited_by?(current_user) %>
            <%= link_to product_favorites_path(@product), method: :delete do %>
              <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
              <%= @product.favorites.count %>
            <% end %>
        <% else %>
            <%= link_to product_favorites_path(@product), method: :post do %>
              <i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
              <%= @product.favorites.count %>
            <% end %>
        <% end %>
        </div>

        <div>
          <% if @product.sales_status == "販売停止中" or @product.stock_quantity == 0 %>
                <p>販売停止中</p>
          <% else %>
            <%= @product.sales_status %>
            在庫数<%= @product.stock_quantity %> 個
          <% end %>
        </div>

        <div>
          <% if Cart.where(user_id: current_user.id).find_by(product_id: @product.id) %>
          <p> あなたのカートには　<%= @usercart.quantity %> 個入っています。</p>
          <% end %>
        </div>

        <% unless @product.sales_status == "販売停止中" or @product.stock_quantity == 0 %>
          <div style="margin: 10px 0px">
          <%= form_for @cart, url:user_carts_path(user_id: current_user.id) do |f| %>
             <div class="col-xs-2" style="padding: 0 0 0 0;" >
           		 <%= f.number_field :quantity, min: 1, max: @temporary_quantity, class: "form-control", style: "width: 80px;" %>
             </div>
             <div class="col-xs-2" style="padding: 0 0 0 0;margin: 0 -30px 0 0;">
           		 <%= f.hidden_field :product_id, :value => @product.id %>
             </div>
       		     <%= f.submit "カートに追加", class: "btn btn-default" %>
          <% end %>
          </div>
        <% end %>

               <% @discs.each do |d| %>
               <div class="d-inline-block col-xs-5" style="margin: 0 0 0 0;padding: 0 0 0 0;">
                 <ul class="list-unstyled">
                   <li>
                    ディスクNo.<%= d.disc_number %>
                   </li>
                    <% d.musics.each do |m| %>
                   <li>
                    <%= m.title %>
                   </li>
                   <% end %>
								 </ul>
               </div>
               <% end %>

    <div class="col-xs-1"></div>

  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1" >
  <div class="d-center-block">
      <%= form_for (@review) do |f| %>
				<h3>商品レビュー</h3>

  				<% if notice %>
  		        <div class="alert alert-info alert-dismissible" role="alert">
  		          <button type="button" class="close" data-dismiss="alert">
  		            <span aria-hidden="true">&times;</span>
  		            <span class="sr-only">close</span>
  		          </button>
  		          <%= notice %>
  		        </div>
  		    <% end %>
  		    <% if alert %>
  		    <div class="alert alert-danger alert-dismissible" role="alert">
  		      <button type="button" class="close" data-dismiss="alert">
  		        <span aria-hidden="true">&times;</span>
  		        <span class="sr-only">close</span>
  		      </button>
  		      <%= alert %>
  		    </div>
  		    <% end %>

  				<%= f.text_area :review, :size => "130x5",  class: "form-control", placeholder:"新規レビュー投稿" %>
  				<%= f.hidden_field :product_id, :value => @product.id %>
  				<%= f.submit "投稿", class: "btn btn-default", style: "margin-top: 10px;" %>
				<% end %>




        <h3>みんなのレビュー</h3>

        <% @reviews.each do |review| %>

          <table class="table table-bordered">
            <tbody>
              <tr>
                <td width="15%"> <%= review.user.last_name %><%= review.user.first_name %></td>
                <td width="85%"> <%= review.review %> </td>
              </tr>
            </tbody>
          </table>

          <% end %>
     </div>
  </div>
</div>


<% else %>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="col-xs-1">
    </div>

    <div class="col-xs-6" >
      <div style="margin: 40px">
        <%= attachment_image_tag @product,:image, :fill,400,400 %>
      </div>
    </div>

      <div class="col-xs-4" style="margin-top: 40px">


        <div>
        <p class="" style="margin: 0 0 0 0;"> <%= @genre.genre %> </p>
        <h2 class="" style="margin: 15px 0 15px 0;"> <%= @product.album %> </h2>
        <p class="" style="margin: 10px 0 10px 0;"> <%= @label.label %></p>
        <p class="" style="margin: 10px 0 10px 0;"> ¥<%= get_producttax(@product) %>（税込）</p>
        <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
        <%= @product.favorites.count %>
        </div>

           <div>
          <% if @product.sales_status == "販売停止中" or @product.stock_quantity == 0 %>
                <p>販売停止中</p>
          <% else %>
            <%= @product.sales_status %>
            在庫数<%= @product.stock_quantity %> 個
          <% end %>
        </div>


        <div style="margin: 10px 0px">
          <div class="col-xs-2" style="padding: 0 0 0 0;margin: 0 0 0 0;" >
          <%= number_field :cart, :quantity, min: 0, max: @product.stock_quantity, class: "form-control", style: "width: 80px;" %>
          </div>
          <div class="col-xs-2" style="padding: 0 0 0 0;margin: 0 30px 0 30px;" >
            <%= link_to "カートに追加", new_user_session_path, aria_hidden: "true", class: "btn btn-default" %>
          </div>
        </div>
      </div>

      <div class="col-xs-4">
               <% @discs.each do |d| %>
               <div class="d-inline-block col-xs-5" style="margin: 10px 0 0 0;padding: 0 0 0 0;">
                 <ul class="list-unstyled">
                     <li>
                        ディスクNo.<%= d.disc_number %>
                     </li>
                     <% d.musics.each do |m| %>
                     <li>
                        <%= m.title %>
                     </li>
                     <% end %>
                 </ul>
               </div>
               <% end %>
      </div>

      </div>
      <div class="col-xs-1">
     </div>
</div>



<div class="row">
  <div class="col-md-8 col-md-offset-2" >
    <div class="d-center-block">

        <h3>みんなのレビュー</h3>

          <% @reviews.each do |review| %>

          <table class="table table-bordered">
            <tbody>
              <tr>
                <td width="15%"> <%= review.user.last_name %><%= review.user.first_name %></td>
                <td width="85%"> <%= review.review %> </td>
              </tr>
            </tbody>
          </table>

          <% end %>


    </div>
  </div>
</div>

<% end %>